[package]
name = "wasm-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
wasmtime = { version = "36.0.2", features = [
  "component-model",
  "cranelift",
  "std",
  "runtime",
] }
wasmtime-wasi = "36.0.2"
