[package]
name = "runner"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[[bin]]
name = "runner"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
pyo3.workspace = true
wasm-python.workspace = true

[build-dependencies]
wlr-libpy.workspace = true
