[package]
name = "runner"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "strategy:strategy"

[package.metadata.component.dependencies]

[lints]
workspace = true

[dependencies]
pyo3.workspace = true
wasm-python.workspace = true
wlr-libpy = { git = "https://github.com/vmware-labs/webassembly-language-runtimes.git", features = [
  "py_main",
] }

[build-dependencies]
wlr-libpy = { git = "https://github.com/vmware-labs/webassembly-language-runtimes.git", features = [
  "build",
] }
