[package]
name = "wasm-python"
version = "0.1.1"
edition = "2021"

[dependencies]
pyo3.workspace = true
wit-bindgen.workspace = true
wlr-libpy = { git = "https://github.com/vmware-labs/webassembly-language-runtimes.git", features = [
  "py_main",
] }
